services:
  php1:
    build:
      context: .
    container_name: PHP1
    tty: true
    restart: always
    ports:
      - "8800:80"

  php2:
    build:
      context: .
    container_name: PHP2
    tty: true
    restart: always
    ports:
      - "8900:80"

  mysqlbdd:
    image: mysql
    container_name: DB_mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_pwd
    ports:
      - "3306:3306"
    restart: unless-stopped

  ansible:
    image: webdevops/ansible
    container_name: ansible
    tty: true
    restart: always