services:
  php1:
    build:
      context: ./laravel/
    container_name: PHP1
    tty: true
    restart: always
    ports:
      - "8800:80"
    depends_on:
      - db

  php2:
    build:
      context: ./laravel/
    container_name: PHP2
    tty: true
    restart: always
    ports:
      - "8900:80"
    depends_on:
      - db

  db:
    container_name: DB
    image: mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_pwd
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ansible:
    build:
      context: ./ansible/
    container_name: ansible
    tty: true
    restart: always
